export const ROUTES = {
  SPLASH:           '/',
  MAP:              '/map',
  ROUTE_LIST:       '/map/routes',
  ROUTE_DETAIL:     '/map/routes/:routeId',
  TRANSFER_DETAIL:  '/map/routes/transfer',
  TICKETS:          '/tickets',
  BUY_TICKETS:      '/tickets/buy',
  TICKET_QUANTITY:  '/tickets/buy/quantity',
  PAY:              '/tickets/buy/pay',
  MY_TICKETS:       '/tickets/my',
  PURCHASE_HISTORY: '/tickets/my/history',
  ACTIVE_TICKET:    '/tickets/my/active',
  QR_SCAN:          '/tickets/qr',
  FEEDBACK:         '/feedback',
  RATING:           '/feedback/rating',
  COMPLAINTS:       '/feedback/complaints',
  OCCUPANCY:        '/feedback/occupancy',
  PROFILE:          '/profile',
  PAYMENT_METHODS:  '/profile/payment',
  ADD_LEOCARD:      '/profile/payment/leocard',
  ADD_BANK_CARD:    '/profile/payment/bank-card',
  EDIT_PROFILE:     '/profile/edit',
  ACCESSIBILITY:    '/profile/accessibility',
  SETTINGS:         '/profile/settings',
  LOGIN:            '/auth/login',
  REGISTER:         '/auth/register',
} as const
